name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild build \
            -project todo.xcodeproj \
            -scheme todo \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -skipPackagePluginValidation \
            CODE_SIGNING_ALLOWED=NO

      - name: Test
        run: |
          xcodebuild test \
            -project todo.xcodeproj \
            -scheme todo \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -skipPackagePluginValidation \
            CODE_SIGNING_ALLOWED=NO
